#!/usr/bin/env python3

import fire
from rich.console import Console


class AipCli(object):
    """AIP command line tool

    Integrate all useful tools here

    Commands
    --------
    deploy
        Deploy the stack to AWS CloudFormation
    bumptag
        Bump and push the tag to generate the new docker image
    build
        Build the docker image
    unittest
        Run unit tests
    integration
        Run some integration tests

    Options
    -------
    --dry-run
        Test stack code and check the correctness (for deploy command)

    """

    def test(self, unittest=False, integration=False):
        """Run tests

        Usage
        -----
        Run unit tests
          ./awscli test --unittest (or ./awscli test -u)

        Run integration tests
          ./awscli test --integration (or ./awscli test -i)

        """

        console = Console()

        if unittest:
            import unittest

            console.log('Runnig unit tests...')
            suite = unittest.TestLoader().discover('tests')
            unittest.TextTestRunner().run(suite)

        if integration:
            from tests import integrations as intg

            console.log('Runnig integration tests...')
            intg.test_vpc_subnets()


if __name__ == '__main__':
    fire.Fire(AipCli)
