version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo Nothing to do in pre_build phase ...
  build:
    commands:
      - echo Build started on `date`
      - pip install -r requiments.txt
  post_build:
    commands:
      - echo Build completed on `date`
